### PR TITLE
implement toggle feature for effect, closes #6

### LINKED ISSUE #6: New Feature: Toggle for effect on/off
First of all thanks for the great toll, i really enjoyed using it. 
But there is one thing i would like to add. In case you want to use those css-filters for hover-effcts it is really hard to compare the before-and-after look. So an "Effect on/off"-toggle would be really helpful. What do you think?

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by ghosh** [comment]
Hey thanks for submitting this PR. I'm a little these days. Will merge soon.

**Comment by DanielRuf** [comment]
Bump.

**Comment by DanielRuf** [comment]
Bump.

I would be also interested to help maintaining this project.

**Comment by DanielRuf** [comment]
Bump.

**Pull request closed without merging**
